BEGIN;
--
-- Create model City
--
CREATE TABLE "api_city" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(30) NOT NULL);
--
-- Create model Street
--
CREATE TABLE "api_street" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(50) NOT NULL, "city_id" bigint NOT NULL);
--
-- Create model Shop
--
CREATE TABLE "api_shop" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(50) NOT NULL, "address" varchar(30) NOT NULL, "opening_hour" time NOT NULL, "closing_hour" time NOT NULL, "city_id" bigint NOT NULL, "street_id" bigint NOT NULL);
ALTER TABLE "api_street" ADD CONSTRAINT "api_street_city_id_f8585439_fk_api_city_id" FOREIGN KEY ("city_id") REFERENCES "api_city" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "api_street_city_id_f8585439" ON "api_street" ("city_id");
ALTER TABLE "api_shop" ADD CONSTRAINT "api_shop_city_id_b715a4c4_fk_api_city_id" FOREIGN KEY ("city_id") REFERENCES "api_city" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "api_shop" ADD CONSTRAINT "api_shop_street_id_e5009fa5_fk_api_street_id" FOREIGN KEY ("street_id") REFERENCES "api_street" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "api_shop_city_id_b715a4c4" ON "api_shop" ("city_id");
CREATE INDEX "api_shop_street_id_e5009fa5" ON "api_shop" ("street_id");
COMMIT;
